version: 2.1

executors:
  bazel-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo

jobs:
  build:
    executor: bazel-executor
    steps:
      - checkout

      - run:
          name: Install Bazelisk (auto Bazel version manager)
          command: |
            curl -Lo bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64
            chmod +x bazelisk
            sudo mv bazelisk /usr/local/bin/bazel

      - run:
          name: Run Bazel Build
          command: |
            bazel build //...

workflows:
  build-workflow:
    jobs:
      - build
