version: 2.1

executors:
  bazel-executor:
    docker:
      - image: cimg/base:stable  # You can change this to any base you need
    working_directory: ~/repo

jobs:
  build:
    executor: bazel-executor
    steps:
      - checkout

      - run:
          name: Install Bazelisk
          command: |
            curl -Lo bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
            chmod +x bazel
            sudo mv bazel /usr/local/bin/bazel

      - run:
          name: Run Bazel build
          command: bazel build //...

workflows:
  build-workflow:
    jobs:
      - build
