version: 2.1

executors:
  bazel-executor:
    docker:
      - image: cimg/base:stable  # or ubuntu, debian, etc.
    working_directory: ~/repo

jobs:
  build:
    executor: bazel-executor
    steps:
      - checkout

      - run:
          name: Install Bazel
          command: |
            sudo apt update
            sudo apt install -y curl gnupg
            curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel.gpg
            sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
            echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
            sudo apt update && sudo apt install -y bazel

      - run:
          name: Run Bazel Build
          command: |
            bazel build //...

workflows:
  build-workflow:
    jobs:
      - build
