version: 2.1

executors:
  bazel-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo

jobs:
  build:
    executor: bazel-executor
    steps:
      - checkout

      - run:
          name: Install Bazelisk
          command: |
            sudo apt update
            sudo apt install -y curl unzip
            curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-linux-amd64"
            chmod +x bazelisk-linux-amd64
            sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel

      - run:
          name: Run Bazel Build
          command: |
            bazel build //...

workflows:
  build-workflow:
    jobs:
      - build