version: 2.1

executors:
  bazel-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo

jobs:
  build:
    executor: bazel-executor
    steps:
      - checkout

      - run:
          name: Install Bazelisk
          command: |
            sudo apt update
            sudo apt install -y curl unzip
            curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-linux-amd64"
            chmod +x bazelisk-linux-amd64
            sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel

      - run:
          name: Run Bazel Build
          command: |
            bazel build //...

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: Install Kubectl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/kubectl

      - run:
          name: Deploy to Kubernetes
          command: |
            kubectl apply -f k8s/deployment.yaml

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build